In [1]:

import tensorflow as tf
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import text_to_word_sequence
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential, Model
from keras.layers import Dense, LSTM, Input, Embedding, TimeDistributed, Flatten, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.models import Sequential
import numpy as np
from tensorflow.keras.utils import to_categorical

In [2]:
import pandas as pd
pd.__version__
df = pd.read_csv('C:/tweet.txt', sep="\n",header=None)
df

0
0   During our time in the White House, Michelle a...
1   There is a lot of disinformation out there, bu...
2   Climate change is a real threat to us all—but ...
3   I’m proud to announce that the Obama President...
4   Black-owned independent bookstores play a crit...
..                                                ...
61  It might be Labor Day weekend, but let’s all r...
62  Completing the Census is crucial because it wi...
63  Joe and Kamala have what it takes to lead this...
64  If you can volunteer as a poll worker for earl...
65  Chadwick came to the White House to work with ...

[66 rows x 1 columns]

In [3]:

list_listword=[]#liste des listes des mots de chaque tweet
list_tweets=df.values.tolist()#liste des tweets
list_tweets

[['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.'],
 ["There is a lot of disinformation out there, but here’s the truth: You should get a COVID vaccine as soon as it's available to you. It could save your life—or a loved one’s."],
 ['Climate change is a real threat to us all—but feeling helpless or overwhelmed isn’t going to solve it. As long as we stay hopeful and keep working with the urgency the challenge demands, we can make a difference.'],
 ['I’m proud to announce that the Obama Presidential Center will officially break ground in 2021. Our hope is that the center will breathe new life into historic Jackson Park while delivering jobs, growth, and much more to the South Side. Let’s get to work.'],
 ['Black-owned independent bookstores play a critical role in communities all across our countr

In [4]:
print(list_tweets[0])
for i in range(0,len(list_tweets)):
  list_listword.append(list_tweets[i][0].split())
list_listword


['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.']


[['During',
  'our',
  'time',
  'in',
  'the',
  'White',
  'House,',
  'Michelle',
  'and',
  'I',
  'were',
  'proud',
  'to',
  'display',
  'artwork',
  'from',
  'artists',
  'like',
  'Alma',
  'Thomas',
  'and',
  'Charles',
  'Alston—whose',
  'work',
  'provoked',
  'thought,',
  'challenged',
  'our',
  'assumptions,',
  'and',
  'shaped',
  'how',
  'we',
  'define',
  'our',
  'narrative',
  'as',
  'a',
  'country.'],
 ['There',
  'is',
  'a',
  'lot',
  'of',
  'disinformation',
  'out',
  'there,',
  'but',
  'here’s',
  'the',
  'truth:',
  'You',
  'should',
  'get',
  'a',
  'COVID',
  'vaccine',
  'as',
  'soon',
  'as',
  "it's",
  'available',
  'to',
  'you.',
  'It',
  'could',
  'save',
  'your',
  'life—or',
  'a',
  'loved',
  'one’s.'],
 ['Climate',
  'change',
  'is',
  'a',
  'real',
  'threat',
  'to',
  'us',
  'all—but',
  'feeling',
  'helpless',
  'or',
  'overwhelmed',
  'isn’t',
  'going',
  'to',
  'solve',
  'it.',
  'As',
  'long',
  'as',
  'we'

In [5]:
length=20+1
lines=[]#les tweets decale par 11 mots
for j in range(len(list_tweets)):
    for i in range(length,len(list_listword[j])):
        seq=list_listword[j][i-length:i]
        line=' '.join(seq)
        lines.append(line)
print(lines[0])
print(lines[1])

During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and
our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles


In [6]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)
sequences = tokenizer.texts_to_sequences(lines)
print(sequences)
#sequences=np.array(sequences)


[[236, 7, 90, 6, 2, 373, 297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3], [7, 90, 6, 2, 373, 297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375], [90, 6, 2, 373, 297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413], [6, 2, 373, 297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57], [2, 373, 297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463], [373, 297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463, 492], [297, 170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463, 492, 523], [170, 3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463, 492, 523, 7], [3, 9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463, 492, 523, 7, 573], [9, 213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463, 492, 523, 7, 573, 3], [213, 206, 1, 462, 437, 29, 374, 71, 341, 342, 3, 375, 413, 57, 463

In [7]:
#y = sequences.reshape(-1, length, 1)
print(len(sequences[0]))
vocab_size=len(tokenizer.word_index)

21


In [8]:

sequences = np.array(sequences[:50])
X, y = sequences[:, :-1], sequences[:,-1]

#y =sequences[:,20:21]


print(y)

[  3 375 413  57 463 492 523   7 573   3 185  30  13 716   7 776  21   4
  21 118 193   1   8  14  83 343  17 777   4 818  21  13 106 465   3 113
 194  24   2 636   2 689 717  13  22  19   4 123  36 243]


In [9]:
vocab_size = len(tokenizer.word_index) + 1
y = to_categorical(y, num_classes=vocab_size)
seq_length = X.shape[1]
seq_length

20

In [10]:
model = Sequential()
model.add(Embedding(vocab_size, 20, input_length=seq_length))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100, activation='relu'))
#model.add(TimeDistributed(Dense(1)))
model.add(Dense(vocab_size, activation='softmax'))

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 20)            16720     
_________________________________________________________________
lstm (LSTM)                  (None, 20, 100)           48400     
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense (Dense)                (None, 100)               10100     
_________________________________________________________________
dense_1 (Dense)              (None, 836)               84436     
Total params: 240,056
Trainable params: 240,056
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.33)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
model.fit(X_train, y_train, batch_size = 256, epochs = 1000)

(33, 20) (17, 20) (33, 836) (17, 836)
Epoch 1/1000
1/1 [==============================] - 0s 1ms/step - loss: 5.8817 - accuracy: 0.6970
Epoch 2/1000
1/1 [==============================] - 0s 1ms/step - loss: 5.4240 - accuracy: 0.7273
Epoch 3/1000
1/1 [==============================] - 0s 996us/step - loss: 4.8855 - accuracy: 0.7576
Epoch 4/1000
1/1 [==============================] - 0s 1ms/step - loss: 4.3395 - accuracy: 0.7576
Epoch 5/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.7493 - accuracy: 0.7576
Epoch 6/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.1497 - accuracy: 0.7576
Epoch 7/1000
1/1 [==============================] - 0s 1ms/step - loss: 2.5990 - accuracy: 0.7576
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1182 - accuracy: 0.7273
Epoch 9/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.7089 - accuracy: 0.7576
Epoch 10/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.415

In [35]:
seed_text=lines[7]
seed_text

'Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our'

In [36]:
#n_words= nb mta3 les mots eli bech predictihom 
#seed_text = jomla ta3tihelo bech ikmel 3liha w tajem ta3tihelo fer4a ya3ni yasna3lek howa jomla jdida 
def generate_text_seq(model, tokenizer, text_seq_length, seed_text, n_words):
  text = []

  for _ in range(n_words):
    encoded = tokenizer.texts_to_sequences([seed_text])[0]
    encoded = pad_sequences([encoded], maxlen = text_seq_length, truncating='pre')
    y_predict = model.predict_classes(encoded)
    predicted_word = ''
    for word, index in tokenizer.word_index.items():
      if index == y_predict:
        predicted_word = word
        break
    seed_text = seed_text + ' ' + predicted_word
    text.append(predicted_word)
  #print(seed_text)
  return ' '.join(text)

In [39]:
text=generate_text_seq(model, tokenizer, seq_length, "",10)

print(text)

it we define our loved as a as we stay


In [17]:
fake_tweets = pd.read_csv('c:/fake_tweets.txt', sep="\n",header=None)
fake_tweets

0
0   Georgia voters—If you're in line before the po...
1   Georgia, I WON THIS ELECTION, BY A LOT! this i...
2   Press Conference at Four Season’s Landscaping,...
3   Tomorrow is Election Day in Georgia and the st...
4   If you’re a Georgia voter, Bad things took pla...
5   After a year that has tested us in unimaginabl...
6   We’re just one week away from the U.S. Senate ...
7   The redistricting process in 2021 will be a sn...
8   Imagine thinking you should be the one to expl...
9   It’s unconscionable that there are families wo...
10  With COVID cases surging worse than ever, gett...
11  including Pennsylvania Like everyone else, we ...
12  Happy Hanukkah to all those celebrating around...
13  In A Promised Land, Georgia Counties Using Sam...
14  With COVID-19 cases reaching an all-time high ...
15  I loved talking to @mashagessen about one of t...
16  I spoke with @iamsambee about how she balances...
17  This Labor Day, let’s It did my heart good, an...
18  I’m sending prayers today to the families of t...
19  shape our communities for the next decade.This...
20  Joe and Kamala have what it takes to lead this...
21  If you can volunteer as a poll worker for earl...
22  For yourself, your family, and your country, p...
23                         That's the good stuff, man
24  Damn, that was good Right in the middle of a p...
25  Michelle and I hope that the President, First ...
26  You're all strawberry and no preserves, ya fog...
27  I’m proud to endorse these outstanding Democra...
28  All right, let's try something new. If you’re ...
29  If you're looking for a way to get involved in...
30  You jackknifed the wrong turnip truck, ya dies...
31  I’m proud to announce that the Obama President...
32  Black-owned independent bookstores play a crit...
33  so I dropped in to surprise the folks from @Ma...
34  We’re investing over $60 billion to help small...
35  In her extraordinary career,The American Rescu...
36  Hank Aaron was one of the best baseball player...
37  This is a time for boldness and President Bide...
38  By rejoining the Paris climate accords on day ...
39  Today was a good day. And it was only possible...
40  This morning, I met virtually with the Quad in...
41  Because you marched. The United States, Japan,...
42  This afternoon, I’m joining Vice President Har...
43  Congratulations to my friend, President @JoeBi...
44  This is the United States of America. There’s ...
45  Tonight, I am announcing that I will direct al...

In [18]:
list_fake_tweets=fake_tweets[0].values.tolist()#liste des tweets
list_fake_tweets
labels_fake=[0 for i in range(len(list_fake_tweets))]
print(len(labels_fake))

46


In [19]:
real_tweets = pd.read_csv('c:/real_tweets.txt', sep="\n",header=None)
real_tweets

0
0   Today was a good day. And it was only possible...
1   Congratulations to my friend, President @JoeBi...
2   If anyone had a right to question whether our ...
3   Happy birthday to my love, my partner, and my ...
4   My friend John Lewis is surely smiling down on...
5   Georgia voters—If you're in line before the po...
6   Georgia, this is it. Today is Election Day and...
7   If you have questions or run into any issues a...
8   Tomorrow is Election Day in Georgia and the st...
9   If you’re a Georgia voter, you can respond tom...
10  After a year that has tested us in unimaginabl...
11  All right, let's try something new. If you’re ...
12  If you're looking for a way to get involved in...
13  There’s no feeling like finishing a book, and ...
14  Over the last few months, I've learned a thing...
15  The fires across the West Coast are just the l...
16  An important reminder as millions of folks acr...
17  Here are some helpful tips about voting in per...
18  We’ve only got one week left in this election....
19  Republicans love to say right before an electi...
20  From police reform to funding our schools, the...
21  Nobody should have to wait 11 hours to vote, b...

In [20]:
list_real_tweets=real_tweets[0].values.tolist()#liste des tweets
labels_real=[1 for i in range(len(list_real_tweets))]

In [21]:

labels=[0 for i in list_fake_tweets ]
for i in list_real_tweets:
    labels.append(1)

print(len(labels))
labels=np.array(labels)
print(labels)

68
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [22]:
list_real_fake_tweets=[i for i in list_fake_tweets]
for i in list_real_tweets:
    list_real_fake_tweets.append(i)

print(len(list_real_fake_tweets))
#print(list_real_fake_tweets)

68


In [23]:

vocab_size = 1000
encoded_docs = [one_hot(d, vocab_size) for d in list_real_fake_tweets]
print(encoded_docs)

[[420, 215, 362, 503, 141, 531, 290, 548, 143, 278, 847, 318, 166, 831, 921, 996, 996, 434, 181, 290, 904, 728, 154, 92, 975, 44, 469, 304, 290, 116, 235, 440, 755, 542, 191, 83, 761, 702, 391, 469, 304, 949, 646, 290, 420, 88, 595, 778, 278, 722, 335, 679, 836, 7, 524, 319, 492, 800, 963, 457, 168, 888, 235, 59, 200, 989, 854, 50], [420, 119, 442, 854, 267, 733, 92, 746, 854, 597, 761, 814, 597, 267, 248, 708, 152, 440, 830, 800, 94, 224, 708, 864, 266, 235, 290, 860, 271, 363, 107, 152, 388, 67, 814, 708, 579, 503, 69, 594, 733, 219, 555, 152, 586, 503, 58, 278, 92, 58, 989, 234], [698, 412, 278, 66, 756, 852, 497, 252, 391, 469, 304, 949, 594, 927, 293, 580, 957, 278, 152, 467, 496, 646, 290, 420, 88, 595, 778, 278, 722, 335, 679, 836], [538, 597, 267, 248, 503, 420, 708, 290, 632, 67, 168, 450, 984, 494, 698, 412, 814, 503, 497, 278, 66, 349, 434, 852, 172, 101, 412, 753, 123, 191, 188, 246, 942, 19, 235, 244, 108, 708, 482, 290, 832, 575, 308, 800, 975, 355, 800, 975, 316, 519, 58

In [24]:
max_length=0
for i in range(len(encoded_docs)):
  if(len(encoded_docs[i])>max_length):
    max_length=len(encoded_docs[i])
print(max_length)

70


In [25]:

padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
print(padded_docs.shape, padded_docs.dtype)
print(labels.shape, labels.dtype)

[[420 215 362 ...  50   0   0]
 [420 119 442 ...   0   0   0]
 [698 412 278 ...   0   0   0]
 ...
 [421 128 235 ...   0   0   0]
 [783 241 730 ...   0   0   0]
 [305 808 304 ...   0   0   0]]
(68, 70) int32
(68,) int32


In [26]:
model_disc = Sequential()
model_disc.add(Embedding(vocab_size, 8, input_length=max_length))
model_disc.add(Flatten())
model_disc.add(Dense(1, activation='sigmoid'))
# compile the model
model_disc.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model_disc.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 70, 8)             8000      
_________________________________________________________________
flatten (Flatten)            (None, 560)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 561       
Total params: 8,561
Trainable params: 8,561
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
from sklearn.model_selection import train_test_split
padded_docs_train,padded_docs_test,labels_train,labels_test = train_test_split(padded_docs, labels, test_size=0.33)
print(padded_docs_train.shape, padded_docs_test.shape, labels_train.shape, labels_test.shape)
# fit the model
model_disc.fit(padded_docs_train, labels_train, epochs=200, verbose=0)
# evaluate the model
print(padded_docs_test)
print(labels)
print(labels_train)
print(labels_test)
loss, accuracy = model_disc.evaluate(padded_docs_test, labels_test, verbose=0)
print('Accuracy: %f' % (accuracy*100))

(45, 70) (23, 70) (45,) (23,)
[[694 116 200 ...   0   0   0]
 [420 119 442 ...   0   0   0]
 [391 469 304 ...   0   0   0]
 ...
 [632 990 733 ...   0   0   0]
 [154 818 152 ... 308 234 903]
 [818 119 769 ...   0   0   0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 1 0 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 1 1 0 0 0 1 0 0]
[1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0]
Accuracy: 65.217394


In [28]:
def discriminateur_text(model_disc, text_seq_length, seed_text):

  encoded=[one_hot(d, vocab_size) for d in seed_text]
  #print(encoded)
  encoded = pad_sequences(encoded, maxlen = text_seq_length, truncating='pre')
  y=model_disc.predict([encoded])
  print(y)
  for i in y:
    if(i<0.6):
        print("it's fake")
    else:
        print("it's real")
   

In [29]:
print(labels[42:50])
text=list_real_fake_tweets[42:50]
discriminateur_text(model_disc, max_length, text)


[0 0 0 0 1 1 1 1]
[[0.566692  ]
 [0.54060453]
 [0.5541644 ]
 [0.51245815]
 [0.732538  ]
 [0.44983876]
 [0.5192248 ]
 [0.45481935]]
it's fake
it's fake
it's fake
it's fake
it's real
it's fake
it's fake
it's fake
