In [1]:
import tensorflow as tf
from keras.preprocessing.text import one_hot
#from keras.preprocessing.text import text_to_word_sequence
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential, Model
#from keras.layers import Dense, LSTM, Input, Embedding, TimeDistributed, Flatten, Dropout
from keras.layers import Dense,Embedding, Flatten
import numpy as np
#from tensorflow.keras.utils import to_categorical
import pandas as pd

In [2]:
fake_tweets = pd.read_csv('c:/fake_tweets.txt', sep="\n",header=None)
fake_tweets

0
0   Georgia voters—If you're in line before the po...
1   Georgia, I WON THIS ELECTION, BY A LOT! this i...
2   Press Conference at Four Season’s Landscaping,...
3   Tomorrow is Election Day in Georgia and the st...
4   If you’re a Georgia voter, Bad things took pla...
5   After a year that has tested us in unimaginabl...
6   We’re just one week away from the U.S. Senate ...
7   The redistricting process in 2021 will be a sn...
8   Imagine thinking you should be the one to expl...
9   It’s unconscionable that there are families wo...
10  With COVID cases surging worse than ever, gett...
11  including Pennsylvania Like everyone else, we ...
12  Happy Hanukkah to all those celebrating around...
13  In A Promised Land, Georgia Counties Using Sam...
14  With COVID-19 cases reaching an all-time high ...
15  I loved talking to @mashagessen about one of t...
16  I spoke with @iamsambee about how she balances...
17  This Labor Day, let’s It did my heart good, an...
18  I’m sending prayers today to the families of t...
19  shape our communities for the next decade.This...
20  Joe and Kamala have what it takes to lead this...
21  If you can volunteer as a poll worker for earl...
22  For yourself, your family, and your country, p...
23                         That's the good stuff, man
24  Damn, that was good Right in the middle of a p...
25  Michelle and I hope that the President, First ...
26  You're all strawberry and no preserves, ya fog...
27  I’m proud to endorse these outstanding Democra...
28  All right, let's try something new. If you’re ...
29  If you're looking for a way to get involved in...
30  You jackknifed the wrong turnip truck, ya dies...
31  I’m proud to announce that the Obama President...
32  Black-owned independent bookstores play a crit...
33  so I dropped in to surprise the folks from @Ma...
34  We’re investing over $60 billion to help small...
35  In her extraordinary career,The American Rescu...
36  Hank Aaron was one of the best baseball player...
37  This is a time for boldness and President Bide...
38  By rejoining the Paris climate accords on day ...
39  Today was a good day. And it was only possible...
40  This morning, I met virtually with the Quad in...
41  Because you marched. The United States, Japan,...
42  This afternoon, I’m joining Vice President Har...
43  Congratulations to my friend, President @JoeBi...
44  This is the United States of America. There’s ...
45  Tonight, I am announcing that I will direct al...

In [3]:
list_fake_tweets=fake_tweets[0].values.tolist()#liste des tweets
list_fake_tweets
labels_fake=[0 for i in range(len(list_fake_tweets))]
print(len(labels_fake))

46


In [4]:
real_tweets = pd.read_csv('c:/real_tweets.txt', sep="\n",header=None)
real_tweets

0
0   Today was a good day. And it was only possible...
1   Congratulations to my friend, President @JoeBi...
2   If anyone had a right to question whether our ...
3   Happy birthday to my love, my partner, and my ...
4   My friend John Lewis is surely smiling down on...
5   Georgia voters—If you're in line before the po...
6   Georgia, this is it. Today is Election Day and...
7   If you have questions or run into any issues a...
8   Tomorrow is Election Day in Georgia and the st...
9   If you’re a Georgia voter, you can respond tom...
10  After a year that has tested us in unimaginabl...
11  All right, let's try something new. If you’re ...
12  If you're looking for a way to get involved in...
13  There’s no feeling like finishing a book, and ...
14  Over the last few months, I've learned a thing...
15  The fires across the West Coast are just the l...
16  An important reminder as millions of folks acr...
17  Here are some helpful tips about voting in per...
18  We’ve only got one week left in this election....
19  Republicans love to say right before an electi...
20  From police reform to funding our schools, the...
21  Nobody should have to wait 11 hours to vote, b...

In [5]:
list_real_tweets=real_tweets[0].values.tolist()#liste des tweets
labels_real=[1 for i in range(len(list_real_tweets))]

In [6]:

labels=[0 for i in list_fake_tweets ]
for i in list_real_tweets:
    labels.append(1)

print(len(labels))
labels=np.array(labels)
print(labels)

68
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [7]:
list_real_fake_tweets=[i for i in list_fake_tweets]
for i in list_real_tweets:
    list_real_fake_tweets.append(i)

print(len(list_real_fake_tweets))
#print(list_real_fake_tweets)

68


In [8]:
vocab_size = 1000
encoded_docs = [one_hot(d, vocab_size) for d in list_real_fake_tweets]
print(encoded_docs)

[[89, 657, 378, 11, 352, 794, 916, 258, 187, 466, 72, 341, 646, 452, 998, 584, 584, 95, 411, 916, 541, 483, 946, 910, 751, 885, 459, 880, 916, 331, 769, 488, 656, 278, 823, 312, 568, 385, 573, 459, 880, 203, 742, 916, 89, 160, 609, 671, 466, 779, 291, 774, 497, 999, 15, 227, 909, 923, 852, 391, 545, 269, 769, 175, 176, 636, 685, 97], [89, 591, 981, 685, 722, 8, 910, 978, 685, 349, 568, 928, 349, 722, 915, 677, 369, 488, 13, 570, 676, 367, 677, 334, 816, 769, 916, 202, 310, 844, 320, 369, 403, 172, 928, 677, 570, 11, 175, 184, 8, 263, 590, 369, 70, 11, 347, 466, 910, 347, 766, 672], [376, 826, 466, 714, 267, 147, 125, 937, 573, 459, 880, 203, 184, 175, 384, 574, 259, 466, 369, 774, 201, 742, 916, 89, 160, 609, 671, 466, 779, 291, 774, 497], [364, 349, 722, 915, 11, 89, 677, 916, 655, 323, 545, 57, 651, 280, 376, 826, 928, 11, 125, 466, 714, 442, 981, 147, 919, 34, 359, 614, 137, 823, 47, 32, 652, 577, 769, 908, 375, 677, 53, 916, 515, 305, 803, 923, 114, 648, 923, 114, 320, 291, 574, 33

In [9]:
max_length=0
for i in range(len(encoded_docs)):
  if(len(encoded_docs[i])>max_length):
    max_length=len(encoded_docs[i])
print(max_length)

70


In [10]:
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
print(padded_docs.shape, padded_docs.dtype)
print(labels.shape, labels.dtype)

[[ 89 657 378 ...  97   0   0]
 [ 89 591 981 ...   0   0   0]
 [376 826 466 ...   0   0   0]
 ...
 [103 524 769 ...   0   0   0]
 [209 513 307 ...   0   0   0]
 [581 682 880 ...   0   0   0]]
(68, 70) int32
(68,) int32


In [11]:
model_disc = Sequential()
model_disc.add(Embedding(vocab_size, 8, input_length=max_length))
model_disc.add(Flatten())
model_disc.add(Dense(1, activation='sigmoid'))
# compile the model
model_disc.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model_disc.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 70, 8)             8000      
_________________________________________________________________
flatten (Flatten)            (None, 560)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 561       
Total params: 8,561
Trainable params: 8,561
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
from sklearn.model_selection import train_test_split
padded_docs_train,padded_docs_test,labels_train,labels_test = train_test_split(padded_docs, labels, test_size=0.33)
#print(padded_docs_train.shape, padded_docs_test.shape, labels_train.shape, labels_test.shape)
# fit the model
model_disc.fit(padded_docs_train, labels_train, epochs=200, verbose=0)
# evaluate the model
#print(padded_docs_test)
#print(labels)
#print(labels_train)
#print(labels_test)
loss, accuracy = model_disc.evaluate(padded_docs_test, labels_test, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 91.304350


In [19]:
def discriminateur_text(model_disc, text_seq_length, seed_text):

  encoded=[one_hot(d, vocab_size) for d in seed_text]
  #print(encoded)
  encoded = pad_sequences(encoded, maxlen = text_seq_length, truncating='pre')
  y=model_disc.predict([encoded])
  print(y)
  for i in y:
    if(i<0.6):
        print("fake")
    else:
        print("real")
   

In [20]:
print(labels[42:50])
text=list_real_fake_tweets[42:50]
discriminateur_text(model_disc, max_length, text)

[0 0 0 0 1 1 1 1]
[[0.5708491 ]
 [0.13474405]
 [0.4140023 ]
 [0.22709808]
 [0.15231884]
 [0.30928856]
 [0.20015442]
 [0.24949986]]
fake
fake
fake
fake
fake
fake
fake
fake
