In [22]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.models import Sequential
from keras.layers import LSTM,Dense,Input,ConvLSTM2D,Reshape,Activation,Lambda,Softmax
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
from sklearn.model_selection import train_test_split

In [23]:
import pandas as pd
pd.__version__
df = pd.read_csv('C:/Users/LENOVO/Desktop/PCD/tweet.txt', sep="\n",header=None)
df

0
0   During our time in the White House, Michelle a...
1   There is a lot of disinformation out there, bu...
2   Climate change is a real threat to us all—but ...
3   I’m proud to announce that the Obama President...
4   Black-owned independent bookstores play a crit...
..                                                ...
61  It might be Labor Day weekend, but let’s all r...
62  Completing the Census is crucial because it wi...
63  Joe and Kamala have what it takes to lead this...
64  If you can volunteer as a poll worker for earl...
65  Chadwick came to the White House to work with ...

[66 rows x 1 columns]

In [24]:
list_listword=[]#liste des listes des mots de chaque tweet
list_tweets=df[0].values.tolist()#liste des tweets
list_tweets

['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.',
 "There is a lot of disinformation out there, but here’s the truth: You should get a COVID vaccine as soon as it's available to you. It could save your life—or a loved one’s.",
 'Climate change is a real threat to us all—but feeling helpless or overwhelmed isn’t going to solve it. As long as we stay hopeful and keep working with the urgency the challenge demands, we can make a difference.',
 'I’m proud to announce that the Obama Presidential Center will officially break ground in 2021. Our hope is that the center will breathe new life into historic Jackson Park while delivering jobs, growth, and much more to the South Side. Let’s get to work.',
 'Black-owned independent bookstores play a critical role in communities all across our country. I want

In [25]:
print(list_tweets[0])
for i in range(0,len(list_tweets)):
  list_listword.append(list_tweets[i].split())
list_listword

During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.


[['During',
  'our',
  'time',
  'in',
  'the',
  'White',
  'House,',
  'Michelle',
  'and',
  'I',
  'were',
  'proud',
  'to',
  'display',
  'artwork',
  'from',
  'artists',
  'like',
  'Alma',
  'Thomas',
  'and',
  'Charles',
  'Alston—whose',
  'work',
  'provoked',
  'thought,',
  'challenged',
  'our',
  'assumptions,',
  'and',
  'shaped',
  'how',
  'we',
  'define',
  'our',
  'narrative',
  'as',
  'a',
  'country.'],
 ['There',
  'is',
  'a',
  'lot',
  'of',
  'disinformation',
  'out',
  'there,',
  'but',
  'here’s',
  'the',
  'truth:',
  'You',
  'should',
  'get',
  'a',
  'COVID',
  'vaccine',
  'as',
  'soon',
  'as',
  "it's",
  'available',
  'to',
  'you.',
  'It',
  'could',
  'save',
  'your',
  'life—or',
  'a',
  'loved',
  'one’s.'],
 ['Climate',
  'change',
  'is',
  'a',
  'real',
  'threat',
  'to',
  'us',
  'all—but',
  'feeling',
  'helpless',
  'or',
  'overwhelmed',
  'isn’t',
  'going',
  'to',
  'solve',
  'it.',
  'As',
  'long',
  'as',
  'we'

In [26]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(list_tweets)
sequences = tokenizer.texts_to_sequences(list_tweets)
vocab_size=len(tokenizer.word_index)
max_length=0
for i in range(len(sequences)):
  if(len(sequences[i])>max_length):
    max_length=len(sequences[i])
print("max",max_length)
print("seq=",sequences)
print(vocab_size)

max 57
seq= [[144, 7, 46, 5, 2, 145, 146, 106, 3, 16, 147, 107, 1, 344, 345, 29, 346, 56, 347, 348, 3, 349, 350, 51, 351, 352, 353, 7, 354, 3, 209, 47, 18, 355, 7, 356, 24, 4, 30], [86, 12, 4, 69, 6, 357, 40, 86, 36, 358, 2, 359, 9, 210, 41, 4, 87, 211, 24, 360, 24, 148, 212, 1, 9, 10, 70, 88, 17, 361, 4, 362, 363], [89, 57, 12, 4, 213, 364, 1, 34, 365, 214, 366, 35, 367, 215, 149, 1, 368, 10, 24, 216, 24, 18, 150, 369, 3, 108, 217, 22, 2, 370, 2, 371, 372, 18, 23, 19, 4, 151], [90, 107, 1, 373, 13, 2, 218, 219, 152, 37, 374, 375, 376, 5, 153, 7, 58, 12, 13, 2, 152, 37, 377, 109, 110, 111, 378, 379, 380, 154, 220, 381, 382, 3, 221, 52, 1, 2, 383, 384, 71, 41, 1, 51], [222, 385, 386, 387, 388, 4, 223, 155, 5, 112, 15, 113, 7, 30, 16, 389, 1, 224, 21, 156, 72, 16, 390, 5, 1, 225, 2, 91, 29, 391, 2, 226, 392, 393, 157, 394, 114, 4, 115], [227, 228, 229, 230, 116, 395, 396, 397, 3, 398, 399, 26, 59, 400, 401, 117, 402, 403, 73, 57, 231, 60, 404, 2, 92, 3, 405, 2, 158, 11, 232, 406, 74, 20,

In [27]:
X =sequences[:33]
X = pad_sequences(X, maxlen=max_length, padding='post')
print("X=",X)
print(X.shape)
y =sequences[33:]
y = pad_sequences(y, maxlen=max_length, padding='post')
print("y=",y)
print(y.shape)
X=X.reshape(33, max_length, 1)
y=y.reshape(33, max_length, 1)
print(X)
print(y)
print('train_x shape:', X.shape)
print('train_y shape:', y.shape)
X_train,X_test,Y_train,Y_test = train_test_split(X, y, test_size=0.33)
print(X_test.shape)
print(Y_test.shape)
Y_train = to_categorical(Y_train)
Y_test = to_categorical(Y_test)

X= [[144   7  46 ...   0   0   0]
 [ 86  12   4 ...   0   0   0]
 [ 89  57  12 ...   0   0   0]
 ...
 [ 71  15  31 ...   0   0   0]
 [106   3  16 ...   0   0   0]
 [  8  27 617 ...   0   0   0]]
(33, 57)
y= [[ 21 304   4 ...  92   0   0]
 [ 52 134 248 ...   0   0   0]
 [ 50  48 649 ...   0   0   0]
 ...
 [ 68   3 317 ...   0   0   0]
 [ 28   9  23 ...   0   0   0]
 [852 302   1 ...   6  59  61]]
(33, 57)
[[[144]
  [  7]
  [ 46]
  ...
  [  0]
  [  0]
  [  0]]

 [[ 86]
  [ 12]
  [  4]
  ...
  [  0]
  [  0]
  [  0]]

 [[ 89]
  [ 57]
  [ 12]
  ...
  [  0]
  [  0]
  [  0]]

 ...

 [[ 71]
  [ 15]
  [ 31]
  ...
  [  0]
  [  0]
  [  0]]

 [[106]
  [  3]
  [ 16]
  ...
  [  0]
  [  0]
  [  0]]

 [[  8]
  [ 27]
  [617]
  ...
  [  0]
  [  0]
  [  0]]]
[[[ 21]
  [304]
  [  4]
  ...
  [ 92]
  [  0]
  [  0]]

 [[ 52]
  [134]
  [248]
  ...
  [  0]
  [  0]
  [  0]]

 [[ 50]
  [ 48]
  [649]
  ...
  [  0]
  [  0]
  [  0]]

 ...

 [[ 68]
  [  3]
  [317]
  ...
  [  0]
  [  0]
  [  0]]

 [[ 28]
  [  9]
  [ 

NameError: name 'to_categorical' is not defined

In [28]:
from keras import backend as K
import keras.backend as kerback
from keras.models import Model
import tensorflow 
model = Sequential()
x0=Input(shape=(57, 1))
# encoder layer
#model.add(LSTM(10, activation='relu', input_shape=(57, 1)))
x1=LSTM(15, activation='relu', input_shape=(57, 1))(x0)
#x1=LSTM(100, activation='relu', input_shape=(3, 1))
# repeat vector
#model.add(RepeatVector(57))
x2=RepeatVector(57)(x1)
# decoder layer
#model.add(LSTM(100, activation='relu', return_sequences=True))
x3=LSTM(15, activation='relu', return_sequences=True)(x2)
#model.add(LSTM(10, activation='relu', return_sequences=True))
#model.add(TimeDistributed(Dense(1)))
x4=TimeDistributed(Dense(1))(x3)
#x4=TimeDistributed(Dense(1))
unstacked = Lambda(lambda x: tensorflow.unstack(x, axis=2))(x4)
dense_outputs = [Dense(57)(x) for x in unstacked]
#print(unstacked)
merged = Lambda(lambda x: K.stack(x, axis=2))(dense_outputs)
#y6=Softmax(axis=-1)(merged)

model = Model(x0, merged)
model.compile(optimizer='adam', loss='categorical_crossentropy')
#model.compile(optimizer='adam', loss='binary_crossentropy')
print(model.summary())



Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 57, 1)]           0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 15)                1020      
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 57, 15)            0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 57, 15)            1860      
_________________________________________________________________
time_distributed_2 (TimeDist (None, 57, 1)             16        
_________________________________________________________________
lambda_4 (Lambda)            [(None, 57)]              0         
_________________________________________________________________
dense_5 (Dense)              (None, 57)               

In [29]:
#model.fit(X, y, epochs=10, batch_size=1, verbose=2)
#model.fit(X, y, epochs=200, validation_split=0.2, verbose=1, batch_size=3)
#model.fit(X, y, epochs=200, verbose=0)
model.fit(X_train,Y_train,epochs=10, batch_size=15,validation_data=(X_test, Y_test))
#model.fit(X,y, epochs=20, batch_size=32, validation_split=3/9)
#loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)
#print('Accuracy: %f' % (accuracy*100))

Epoch 1/10
2/2 [==============================] - 1s 404ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 2/10
2/2 [==============================] - 0s 51ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 3/10
2/2 [==============================] - 0s 45ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 4/10
2/2 [==============================] - 0s 53ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 5/10
2/2 [==============================] - 0s 58ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 6/10
2/2 [==============================] - 0s 66ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 7/10
2/2 [==============================] - 0s 52ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 8/10
2/2 [==============================] - 0s 50ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 9/10
2/2 [==============================] - 0s 51ms/step - loss: 1.6982e-05 - val_loss: 1.5933e-05
Epoch 10/10
2/2 [==============================] - 0s 

In [30]:
#test_input = np.array([300, 305, 310])
test_input=X[5:9]
print(y[5:9])
print(test_input)
encoded = pad_sequences([test_input], maxlen = 3, truncating='pre')

result = model.predict(test_input, batch_size=3, verbose=0)
#print(test_output)
print(result)

[[[ 52]
  [134]
  [318]
  [319]
  [201]
  [ 33]
  [239]
  [672]
  [  4]
  [ 65]
  [  5]
  [  8]
  [ 25]
  [673]
  [674]
  [  3]
  [675]
  [ 39]
  [676]
  [  6]
  [ 44]
  [ 84]
  [  3]
  [ 16]
  [138]
  [  1]
  [677]
  [ 22]
  [ 44]
  [ 63]
  [103]
  [245]
  [202]
  [ 44]
  [  3]
  [ 41]
  [ 40]
  [ 86]
  [  3]
  [ 14]
  [ 50]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  7]
  [320]
  [678]
  [119]
  [  8]
  [145]
  [146]
  [  4]
  [679]
  [ 13]
  [321]
  [ 33]
  [680]
  [ 44]
  [ 47]
  [  1]
  [267]
  [ 63]
  [ 87]
  [293]
  [681]
  [  7]
  [682]
  [ 68]
  [  3]
  [ 16]
  [683]
  [ 10]
  [684]
  [114]
  [  4]
  [115]
  [ 84]
  [  3]
  [295]
  [ 14]
  [ 11]
  [  4]
  [685]
  [ 95]
  [ 37]
  [ 41]
  [  8]
  [322]
  [203]
  [141]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[ 18]
  [284]
  [686]
  [  1]
  [ 45]
  [687]
  [ 75]
  [  8]
  [ 46]
  [ 75]
  [ 

In [31]:
res=[]
for i in range(len(result)):
    predicted_word = ''
    for j in range(len(result[i])):
     for word, index in tokenizer.word_index.items():
       
        if index == int(result[i][j][0]):
          predicted_word = predicted_word+' '+word
          break
    res.append(predicted_word)   
for i in res:
    print(i)

 to and the and to to a the to the the the to the in
 all from i right us could make this today vote from or are covid get year georgia we it i us there climate year
 the to the to and to to the the to and
 to to the the to to to to to the
