In [1]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.models import Sequential
from keras.layers import LSTM,Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import string

In [2]:
import pandas as pd
pd.__version__
df = pd.read_csv('C:/tweet.txt', sep="\n",header=None)
df

0
0   During our time in the White House, Michelle a...
1   There is a lot of disinformation out there, bu...
2   Climate change is a real threat to us all—but ...
3   I’m proud to announce that the Obama President...
4   Black-owned independent bookstores play a crit...
..                                                ...
61  It might be Labor Day weekend, but let’s all r...
62  Completing the Census is crucial because it wi...
63  Joe and Kamala have what it takes to lead this...
64  If you can volunteer as a poll worker for earl...
65  Chadwick came to the White House to work with ...

[66 rows x 1 columns]

In [3]:
list_listword=[]#liste des listes des mots de chaque tweet
list_tweets=df[0].values.tolist()#liste des tweets
list_tweets

['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.',
 "There is a lot of disinformation out there, but here’s the truth: You should get a COVID vaccine as soon as it's available to you. It could save your life—or a loved one’s.",
 'Climate change is a real threat to us all—but feeling helpless or overwhelmed isn’t going to solve it. As long as we stay hopeful and keep working with the urgency the challenge demands, we can make a difference.',
 'I’m proud to announce that the Obama Presidential Center will officially break ground in 2021. Our hope is that the center will breathe new life into historic Jackson Park while delivering jobs, growth, and much more to the South Side. Let’s get to work.',
 'Black-owned independent bookstores play a critical role in communities all across our country. I want

In [4]:
import re
l=[]
for text in list_tweets:
    text = re.sub(r'http\S+', '', text)   # Remove URLs
    text = re.sub(r'—', ' ', text) 
    text = re.sub(r'@[a-zA-Z0-9_]+', '', text)  # Remove @ mentions
    text = text.strip(" ")   # Remove whitespace resulting from above
    text = re.sub(r' +', ' ', text)   # Remove redundant spaces
    l.append(text)
list_tweets=l
list_tweets

['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.',
 "There is a lot of disinformation out there, but here’s the truth: You should get a COVID vaccine as soon as it's available to you. It could save your life or a loved one’s.",
 'Climate change is a real threat to us all but feeling helpless or overwhelmed isn’t going to solve it. As long as we stay hopeful and keep working with the urgency the challenge demands, we can make a difference.',
 'I’m proud to announce that the Obama Presidential Center will officially break ground in 2021. Our hope is that the center will breathe new life into historic Jackson Park while delivering jobs, growth, and much more to the South Side. Let’s get to work.',
 'Black-owned independent bookstores play a critical role in communities all across our country. I want

In [5]:
print(list_tweets[0])
for i in range(0,len(list_tweets)):
  list_listword.append(list_tweets[i].split())
list_listword

During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.


[['During',
  'our',
  'time',
  'in',
  'the',
  'White',
  'House,',
  'Michelle',
  'and',
  'I',
  'were',
  'proud',
  'to',
  'display',
  'artwork',
  'from',
  'artists',
  'like',
  'Alma',
  'Thomas',
  'and',
  'Charles',
  'Alston',
  'whose',
  'work',
  'provoked',
  'thought,',
  'challenged',
  'our',
  'assumptions,',
  'and',
  'shaped',
  'how',
  'we',
  'define',
  'our',
  'narrative',
  'as',
  'a',
  'country.'],
 ['There',
  'is',
  'a',
  'lot',
  'of',
  'disinformation',
  'out',
  'there,',
  'but',
  'here’s',
  'the',
  'truth:',
  'You',
  'should',
  'get',
  'a',
  'COVID',
  'vaccine',
  'as',
  'soon',
  'as',
  "it's",
  'available',
  'to',
  'you.',
  'It',
  'could',
  'save',
  'your',
  'life',
  'or',
  'a',
  'loved',
  'one’s.'],
 ['Climate',
  'change',
  'is',
  'a',
  'real',
  'threat',
  'to',
  'us',
  'all',
  'but',
  'feeling',
  'helpless',
  'or',
  'overwhelmed',
  'isn’t',
  'going',
  'to',
  'solve',
  'it.',
  'As',
  'long',

In [6]:


tokenizer = Tokenizer()
tokenizer.fit_on_texts(list_tweets)
sequences = tokenizer.texts_to_sequences(list_tweets)
vocab_size=len(tokenizer.word_index)
max_length=0
for i in range(len(sequences)):
  if(len(sequences[i])>max_length):
    max_length=len(sequences[i])
print("max",max_length)
print("seq=",sequences)

X =sequences[:33]
X = pad_sequences(X, maxlen=max_length, padding='post')
print("X=",X)
print(X.shape)
y =sequences[33:]
y = pad_sequences(y, maxlen=max_length, padding='post')
print("y=",y)
print(y.shape)
X=X.reshape(33, max_length, 1)
y=y.reshape(33, max_length, 1)
print(X)
print(y)
print('train_x shape:', X.shape)
print('train_y shape:', y.shape)

max 57
seq= [[146, 7, 46, 5, 2, 147, 148, 106, 3, 17, 149, 107, 1, 348, 349, 30, 350, 58, 351, 352, 3, 353, 354, 208, 52, 355, 356, 357, 7, 358, 3, 209, 47, 18, 359, 7, 360, 22, 4, 27], [87, 12, 4, 69, 6, 361, 40, 87, 35, 362, 2, 363, 8, 210, 41, 4, 88, 211, 22, 364, 22, 150, 212, 1, 8, 10, 70, 89, 16, 90, 32, 4, 365, 366], [91, 59, 12, 4, 213, 367, 1, 36, 14, 35, 214, 368, 32, 369, 215, 151, 1, 370, 10, 22, 216, 22, 18, 152, 371, 3, 108, 217, 23, 2, 372, 2, 373, 374, 18, 24, 19, 4, 153], [92, 107, 1, 375, 15, 2, 218, 219, 154, 37, 376, 377, 378, 5, 155, 7, 60, 12, 15, 2, 154, 37, 379, 109, 90, 110, 380, 381, 382, 156, 220, 383, 384, 3, 221, 53, 1, 2, 385, 386, 71, 41, 1, 52], [222, 387, 388, 389, 390, 4, 223, 157, 5, 111, 14, 112, 7, 27, 17, 391, 1, 224, 21, 158, 72, 17, 392, 5, 1, 225, 2, 93, 30, 2, 226, 393, 394, 159, 395, 113, 4, 114], [227, 228, 229, 230, 115, 396, 397, 398, 3, 399, 400, 28, 61, 401, 3, 402, 116, 403, 54, 404, 73, 59, 231, 54, 405, 2, 94, 3, 406, 2, 160, 11, 232, 

In [11]:
model = Sequential()

model.add(LSTM(57, input_shape=(max_length, 1), return_sequences=True))
#model.add(LSTM(57, activation='relu'))
model.add(Dense(57, activation="relu"))
model.add(Dense(57, activation="relu"))
model.add(TimeDistributed(Dense(1)))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 57, 57)            13452     
_________________________________________________________________
dense_2 (Dense)              (None, 57, 57)            3306      
_________________________________________________________________
dense_3 (Dense)              (None, 57, 57)            3306      
_________________________________________________________________
time_distributed_2 (TimeDist (None, 57, 1)             58        
Total params: 20,122
Trainable params: 20,122
Non-trainable params: 0
_________________________________________________________________
None


In [12]:
#model.fit(X, y, epochs=100, validation_split=0.2, verbose=1, batch_size=3)
model.fit(X, y, epochs=100, batch_size=1, verbose=2)


Epoch 1/100
33/33 - 0s - loss: 72246.6875
Epoch 2/100
33/33 - 0s - loss: 65945.8906
Epoch 3/100
33/33 - 0s - loss: 55676.5703
Epoch 4/100
33/33 - 0s - loss: 53070.9922
Epoch 5/100
33/33 - 0s - loss: 52710.6953
Epoch 6/100
33/33 - 0s - loss: 52683.5781
Epoch 7/100
33/33 - 0s - loss: 52624.2109
Epoch 8/100
33/33 - 0s - loss: 52593.7617
Epoch 9/100
33/33 - 0s - loss: 52526.1367
Epoch 10/100
33/33 - 0s - loss: 52552.0039
Epoch 11/100
33/33 - 0s - loss: 52531.3906
Epoch 12/100
33/33 - 0s - loss: 52528.4141
Epoch 13/100
33/33 - 0s - loss: 52482.1562
Epoch 14/100
33/33 - 0s - loss: 52422.4375
Epoch 15/100
33/33 - 0s - loss: 52498.0039
Epoch 16/100
33/33 - 0s - loss: 52419.7734
Epoch 17/100
33/33 - 0s - loss: 52450.8555
Epoch 18/100
33/33 - 0s - loss: 52469.3242
Epoch 19/100
33/33 - 0s - loss: 52382.1797
Epoch 20/100
33/33 - 0s - loss: 52251.3242
Epoch 21/100
33/33 - 0s - loss: 52161.1016
Epoch 22/100
33/33 - 0s - loss: 52318.0352
Epoch 23/100
33/33 - 0s - loss: 52191.2539
Epoch 24/100
33/33 -

In [13]:

test_input=X[7:9]
print(y[7:9])
print(test_input)
encoded = pad_sequences([test_input], maxlen = 57, truncating='pre')

result = model.predict(test_input, batch_size=3, verbose=0)
print(result)


[[[ 18]
  [286]
  [673]
  [  1]
  [ 45]
  [674]
  [ 75]
  [  9]
  [ 46]
  [ 75]
  [  5]
  [  9]
  [ 26]
  [ 19]
  [  4]
  [ 83]
  [ 38]
  [ 79]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  8]
  [ 70]
  [ 45]
  [  2]
  [153]
  [293]
  [675]
  [326]
  [ 10]
  [ 40]
  [  1]
  [  2]
  [253]
  [ 32]
  [676]
  [116]
  [  3]
  [171]
  [327]
  [ 70]
  [ 45]
  [306]
  [ 49]
  [  4]
  [677]
  [  6]
  [678]
  [201]
  [ 74]
  [  3]
  [ 19]
  [ 82]
  [244]
  [ 11]
  [ 68]
  [  5]
  [  2]
  [141]
  [ 96]
  [132]
  [  6]
  [  9]
  [ 26]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]]
[[[427]
  [236]
  [ 29]
  [ 33]
  [  6]
  [  2]
  [121]
  [231]
  [428]
  [122]
  [1

In [14]:

res=[]
for i in range(len(result)):
    predicted_word = ''
    for j in range(len(result[i])):
     for word, index in tokenizer.word_index.items():
        if index == int(result[i][j][0]):
          predicted_word = predicted_word+' '+word
          break
    res.append(predicted_word)
for i in res:
    print(i)

 honor protect upcoming let's whose these difference 1 power protection no mail far never book ever sure white going were honor it's vaccine down days support americans white line few joe voting home now things across you're person best had home person going help line voter climate a a have a this of the to
 it's jackie when real send much friends available much tested black presidential obama obama well should young protecting extraordinary getting presidency presidency shaped should experts upcoming voted had were protection let's power box even tomorrow no call build role big down person left i’m line about that democracy them us out country my is in the
