In [1]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.models import Sequential
from keras.layers import LSTM,Dense,Input,ConvLSTM2D,Reshape,Activation,Lambda,Softmax
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

In [2]:
import pandas as pd
pd.__version__
df = pd.read_csv('C:/Users/LENOVO/Desktop/PCD/tweet.txt', sep="\n",header=None)
df

0
0   During our time in the White House, Michelle a...
1   There is a lot of disinformation out there, bu...
2   Climate change is a real threat to us all—but ...
3   I’m proud to announce that the Obama President...
4   Black-owned independent bookstores play a crit...
..                                                ...
61  It might be Labor Day weekend, but let’s all r...
62  Completing the Census is crucial because it wi...
63  Joe and Kamala have what it takes to lead this...
64  If you can volunteer as a poll worker for earl...
65  Chadwick came to the White House to work with ...

[66 rows x 1 columns]

In [3]:
list_listword=[]#liste des listes des mots de chaque tweet
list_tweets=df.values.tolist()#liste des tweets
list_tweets

[['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.'],
 ["There is a lot of disinformation out there, but here’s the truth: You should get a COVID vaccine as soon as it's available to you. It could save your life—or a loved one’s."],
 ['Climate change is a real threat to us all—but feeling helpless or overwhelmed isn’t going to solve it. As long as we stay hopeful and keep working with the urgency the challenge demands, we can make a difference.'],
 ['I’m proud to announce that the Obama Presidential Center will officially break ground in 2021. Our hope is that the center will breathe new life into historic Jackson Park while delivering jobs, growth, and much more to the South Side. Let’s get to work.'],
 ['Black-owned independent bookstores play a critical role in communities all across our countr

In [4]:
print(list_tweets[0])
for i in range(0,len(list_tweets)):
  list_listword.append(list_tweets[i][0].split())
list_listword

['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.']


[['During',
  'our',
  'time',
  'in',
  'the',
  'White',
  'House,',
  'Michelle',
  'and',
  'I',
  'were',
  'proud',
  'to',
  'display',
  'artwork',
  'from',
  'artists',
  'like',
  'Alma',
  'Thomas',
  'and',
  'Charles',
  'Alston—whose',
  'work',
  'provoked',
  'thought,',
  'challenged',
  'our',
  'assumptions,',
  'and',
  'shaped',
  'how',
  'we',
  'define',
  'our',
  'narrative',
  'as',
  'a',
  'country.'],
 ['There',
  'is',
  'a',
  'lot',
  'of',
  'disinformation',
  'out',
  'there,',
  'but',
  'here’s',
  'the',
  'truth:',
  'You',
  'should',
  'get',
  'a',
  'COVID',
  'vaccine',
  'as',
  'soon',
  'as',
  "it's",
  'available',
  'to',
  'you.',
  'It',
  'could',
  'save',
  'your',
  'life—or',
  'a',
  'loved',
  'one’s.'],
 ['Climate',
  'change',
  'is',
  'a',
  'real',
  'threat',
  'to',
  'us',
  'all—but',
  'feeling',
  'helpless',
  'or',
  'overwhelmed',
  'isn’t',
  'going',
  'to',
  'solve',
  'it.',
  'As',
  'long',
  'as',
  'we'

In [5]:
length=5+1
lines=[]#les tweets decale par 11 mots
for j in range(len(list_tweets)):
    for i in range(length,len(list_listword[j])):
        seq=list_listword[j][i-length:i]
        line=' '.join(seq)
        lines.append(line)
print(lines[0])
print(lines[1])

During our time in the White
our time in the White House,


In [6]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)
print(lines)
sequences = tokenizer.texts_to_sequences(lines)
#print(sequences)
print(len(sequences[0]))
vocab_size=len(tokenizer.word_index)

['During our time in the White', 'our time in the White House,', 'time in the White House, Michelle', 'in the White House, Michelle and', 'the White House, Michelle and I', 'White House, Michelle and I were', 'House, Michelle and I were proud', 'Michelle and I were proud to', 'and I were proud to display', 'I were proud to display artwork', 'were proud to display artwork from', 'proud to display artwork from artists', 'to display artwork from artists like', 'display artwork from artists like Alma', 'artwork from artists like Alma Thomas', 'from artists like Alma Thomas and', 'artists like Alma Thomas and Charles', 'like Alma Thomas and Charles Alston—whose', 'Alma Thomas and Charles Alston—whose work', 'Thomas and Charles Alston—whose work provoked', 'and Charles Alston—whose work provoked thought,', 'Charles Alston—whose work provoked thought, challenged', 'Alston—whose work provoked thought, challenged our', 'work provoked thought, challenged our assumptions,', 'provoked thought, cha

6


In [7]:

sequences = np.array(sequences[:20])
print(sequences)

X = sequences[:, :3]
#print(X)
#print(X.shape)
#print(y)
#print(y.shape)

y =sequences[:,3:6]
#50 1 5
X=X.reshape(20, 3, 1)
y=y.reshape(20, 3, 1)

print(y)
print(y.shape)
print(X)
print(X.shape)

[[190   7  48   5   2 160]
 [  7  48   5   2 160 127]
 [ 48   5   2 160 127 182]
 [  5   2 160 127 182   3]
 [  2 160 127 182   3  13]
 [160 127 182   3  13 161]
 [127 182   3  13 161 171]
 [182   3  13 161 171   1]
 [  3  13 161 171   1 324]
 [ 13 161 171   1 324 325]
 [161 171   1 324 325  25]
 [171   1 324 325  25 326]
 [  1 324 325  25 326  69]
 [324 325  25 326  69 327]
 [325  25 326  69 327 328]
 [ 25 326  69 327 328   3]
 [326  69 327 328   3 329]
 [ 69 327 328   3 329 330]
 [327 328   3 329 330  67]
 [328   3 329 330  67 331]]
[[[  5]
  [  2]
  [160]]

 [[  2]
  [160]
  [127]]

 [[160]
  [127]
  [182]]

 [[127]
  [182]
  [  3]]

 [[182]
  [  3]
  [ 13]]

 [[  3]
  [ 13]
  [161]]

 [[ 13]
  [161]
  [171]]

 [[161]
  [171]
  [  1]]

 [[171]
  [  1]
  [324]]

 [[  1]
  [324]
  [325]]

 [[324]
  [325]
  [ 25]]

 [[325]
  [ 25]
  [326]]

 [[ 25]
  [326]
  [ 69]]

 [[326]
  [ 69]
  [327]]

 [[ 69]
  [327]
  [328]]

 [[327]
  [328]
  [  3]]

 [[328]
  [  3]
  [329]]

 [[  3]
  [329]
 

In [8]:
from keras import backend as K
import keras.backend as kerback
from keras.models import Model
import tensorflow 
#model = Sequential()
x0=Input(shape=(3, 1))
# encoder layer
#model.add(LSTM(100, activation='relu', input_shape=(3, 1)))
x1=LSTM(100, activation='relu', input_shape=(3, 1))(x0)

# repeat vector
#model.add(RepeatVector(3))
x2=RepeatVector(3)(x1)
# decoder layer
#model.add(LSTM(100, activation='relu', return_sequences=True))
x3=LSTM(100, activation='relu', return_sequences=True)(x2)
#model.add(TimeDistributed(Dense(1)))
x4=TimeDistributed(Dense(1))(x3)

unstacked = Lambda(lambda x: tensorflow.unstack(x, axis=2))(x4)
dense_outputs = [Dense(3)(x) for x in unstacked]
merged = Lambda(lambda x: K.stack(x, axis=2))(dense_outputs)
y6=Softmax(axis=-1)(merged)
model = Model(x0, y6)
model.compile(optimizer='adam', loss='categorical_crossentropy')

print(model.summary())



Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3, 1)]            0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               40800     
_________________________________________________________________
repeat_vector (RepeatVector) (None, 3, 100)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 100)            80400     
_________________________________________________________________
time_distributed (TimeDistri (None, 3, 1)              101       
_________________________________________________________________
lambda (Lambda)              [(None, 3)]               0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                

In [9]:
model.fit(X, y, epochs=200, validation_split=0.2, verbose=1, batch_size=3)

Epoch 1/200
6/6 [==============================] - 1s 202ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 2/200
6/6 [==============================] - 0s 17ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 3/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 4/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 5/200
6/6 [==============================] - 0s 22ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 6/200
6/6 [==============================] - 0s 16ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 7/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 8/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 9/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 10/200
6/6 [===========================

6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 78/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 79/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 80/200
6/6 [==============================] - 0s 20ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 81/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 82/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 83/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 84/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 85/200
6/6 [==============================] - 0s 21ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 86/200
6/6 [==============================] 

6/6 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 154/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 155/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 156/200
6/6 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 157/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 158/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 159/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 160/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 161/200
6/6 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 162/200
6/6 [========================

In [10]:
#test_input = np.array([300, 305, 310])
test_input=X[6:9]
print(y[6:9])
print(test_input)
encoded = pad_sequences([test_input], maxlen = 3, truncating='pre')

result = model.predict(test_input, batch_size=3, verbose=0)
#print(test_output)
print(result)

[[[ 13]
  [161]
  [171]]

 [[161]
  [171]
  [  1]]

 [[171]
  [  1]
  [324]]]
[[[127]
  [182]
  [  3]]

 [[182]
  [  3]
  [ 13]]

 [[  3]
  [ 13]
  [161]]]
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


In [11]:
res=[]
for i in range(len(result)):
    predicted_word = ''
    for j in range(len(result[i])):
     for word, index in tokenizer.word_index.items():
        if index == int(result[i][j][0]):
          predicted_word = predicted_word+' '+word
          break
    res.append(predicted_word)
print(res)
for i in res:
    print(i)

[' to to to', ' to to to', ' to to to']
 to to to
 to to to
 to to to
