In [26]:
from keras.layers import RepeatVector
from keras.layers import TimeDistributed
from keras.models import Sequential
from keras.layers import LSTM,Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np


In [27]:
import pandas as pd
pd.__version__
df = pd.read_csv('C:/tweet.txt', sep="\n",header=None)
df

0
0   During our time in the White House, Michelle a...
1   There is a lot of disinformation out there, bu...
2   Climate change is a real threat to us all—but ...
3   I’m proud to announce that the Obama President...
4   Black-owned independent bookstores play a crit...
..                                                ...
61  It might be Labor Day weekend, but let’s all r...
62  Completing the Census is crucial because it wi...
63  Joe and Kamala have what it takes to lead this...
64  If you can volunteer as a poll worker for earl...
65  Chadwick came to the White House to work with ...

[66 rows x 1 columns]

In [28]:
list_listword=[]#liste des listes des mots de chaque tweet
list_tweets=df.values.tolist()#liste des tweets
list_tweets

[['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.'],
 ["There is a lot of disinformation out there, but here’s the truth: You should get a COVID vaccine as soon as it's available to you. It could save your life—or a loved one’s."],
 ['Climate change is a real threat to us all—but feeling helpless or overwhelmed isn’t going to solve it. As long as we stay hopeful and keep working with the urgency the challenge demands, we can make a difference.'],
 ['I’m proud to announce that the Obama Presidential Center will officially break ground in 2021. Our hope is that the center will breathe new life into historic Jackson Park while delivering jobs, growth, and much more to the South Side. Let’s get to work.'],
 ['Black-owned independent bookstores play a critical role in communities all across our countr

In [29]:
print(list_tweets[0])
for i in range(0,len(list_tweets)):
  list_listword.append(list_tweets[i][0].split())
list_listword

['During our time in the White House, Michelle and I were proud to display artwork from artists like Alma Thomas and Charles Alston—whose work provoked thought, challenged our assumptions, and shaped how we define our narrative as a country.']


[['During',
  'our',
  'time',
  'in',
  'the',
  'White',
  'House,',
  'Michelle',
  'and',
  'I',
  'were',
  'proud',
  'to',
  'display',
  'artwork',
  'from',
  'artists',
  'like',
  'Alma',
  'Thomas',
  'and',
  'Charles',
  'Alston—whose',
  'work',
  'provoked',
  'thought,',
  'challenged',
  'our',
  'assumptions,',
  'and',
  'shaped',
  'how',
  'we',
  'define',
  'our',
  'narrative',
  'as',
  'a',
  'country.'],
 ['There',
  'is',
  'a',
  'lot',
  'of',
  'disinformation',
  'out',
  'there,',
  'but',
  'here’s',
  'the',
  'truth:',
  'You',
  'should',
  'get',
  'a',
  'COVID',
  'vaccine',
  'as',
  'soon',
  'as',
  "it's",
  'available',
  'to',
  'you.',
  'It',
  'could',
  'save',
  'your',
  'life—or',
  'a',
  'loved',
  'one’s.'],
 ['Climate',
  'change',
  'is',
  'a',
  'real',
  'threat',
  'to',
  'us',
  'all—but',
  'feeling',
  'helpless',
  'or',
  'overwhelmed',
  'isn’t',
  'going',
  'to',
  'solve',
  'it.',
  'As',
  'long',
  'as',
  'we'

In [30]:
length=5+1
lines=[]#les tweets decale par 11 mots
for j in range(len(list_tweets)):
    for i in range(length,len(list_listword[j])):
        seq=list_listword[j][i-length:i]
        line=' '.join(seq)
        lines.append(line)
print(lines[0])
print(lines[1])

During our time in the White
our time in the White House,


In [31]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)
sequences = tokenizer.texts_to_sequences(lines)
#sequences=np.array(sequences)
print(len(sequences[0]))
vocab_size=len(tokenizer.word_index)

6


In [32]:
sequences = np.array(sequences[:20])
print(sequences)

X = sequences[:, :3]
#print(X)
#print(X.shape)
#print(y)
#print(y.shape)

y =sequences[:,3:6]
#50 1 5
X=X.reshape(20, 3, 1)
y=y.reshape(20, 3, 1)

print(y)
print(y.shape)
print(X)
print(X.shape)


[[190   7  48   5   2 160]
 [  7  48   5   2 160 127]
 [ 48   5   2 160 127 182]
 [  5   2 160 127 182   3]
 [  2 160 127 182   3  13]
 [160 127 182   3  13 161]
 [127 182   3  13 161 171]
 [182   3  13 161 171   1]
 [  3  13 161 171   1 323]
 [ 13 161 171   1 323 324]
 [161 171   1 323 324  25]
 [171   1 323 324  25 325]
 [  1 323 324  25 325  68]
 [323 324  25 325  68 326]
 [324  25 325  68 326 327]
 [ 25 325  68 326 327   3]
 [325  68 326 327   3 328]
 [ 68 326 327   3 328 329]
 [326 327   3 328 329  67]
 [327   3 328 329  67 330]]
[[[  5]
  [  2]
  [160]]

 [[  2]
  [160]
  [127]]

 [[160]
  [127]
  [182]]

 [[127]
  [182]
  [  3]]

 [[182]
  [  3]
  [ 13]]

 [[  3]
  [ 13]
  [161]]

 [[ 13]
  [161]
  [171]]

 [[161]
  [171]
  [  1]]

 [[171]
  [  1]
  [323]]

 [[  1]
  [323]
  [324]]

 [[323]
  [324]
  [ 25]]

 [[324]
  [ 25]
  [325]]

 [[ 25]
  [325]
  [ 68]]

 [[325]
  [ 68]
  [326]]

 [[ 68]
  [326]
  [327]]

 [[326]
  [327]
  [  3]]

 [[327]
  [  3]
  [328]]

 [[  3]
  [328]
 

In [33]:

model = Sequential()

# encoder layer
model.add(LSTM(100, activation='relu', input_shape=(3, 1)))

# repeat vector
model.add(RepeatVector(3))

# decoder layer
model.add(LSTM(100, activation='relu', return_sequences=True))

model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 100)               40800     
_________________________________________________________________
repeat_vector_1 (RepeatVecto (None, 3, 100)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 3, 100)            80400     
_________________________________________________________________
time_distributed_1 (TimeDist (None, 3, 1)              101       
Total params: 121,301
Trainable params: 121,301
Non-trainable params: 0
_________________________________________________________________
None


In [34]:
model.fit(X, y, epochs=100, validation_split=0.2, verbose=1, batch_size=3)
#model.fit(X, y, epochs=100, batch_size=1, verbose=2)


Epoch 1/100
6/6 [==============================] - 0s 59ms/step - loss: 38866.9609 - val_loss: 69275.0000
Epoch 2/100
6/6 [==============================] - 0s 6ms/step - loss: 36980.3281 - val_loss: 63016.0703
Epoch 3/100
6/6 [==============================] - 0s 5ms/step - loss: 33714.0312 - val_loss: 46642.5938
Epoch 4/100
6/6 [==============================] - 0s 5ms/step - loss: 26295.1953 - val_loss: 40269.8242
Epoch 5/100
6/6 [==============================] - 0s 5ms/step - loss: 23778.9316 - val_loss: 33881.0469
Epoch 6/100
6/6 [==============================] - 0s 5ms/step - loss: 20806.9902 - val_loss: 29147.2461
Epoch 7/100
6/6 [==============================] - 0s 5ms/step - loss: 20461.0938 - val_loss: 28245.5840
Epoch 8/100
6/6 [==============================] - 0s 5ms/step - loss: 19524.4766 - val_loss: 28567.0586
Epoch 9/100
6/6 [==============================] - 0s 5ms/step - loss: 18943.3223 - val_loss: 28302.9844
Epoch 10/100
6/6 [==============================] - 0s

In [37]:
#test_input = np.array([300, 305, 310])
test_input=X[6:9]
print(y[6:9])
print(test_input)
encoded = pad_sequences([test_input], maxlen = 3, truncating='pre')

result = model.predict(test_input, batch_size=3, verbose=0)
#print(test_output)
print(result)


[[[ 13]
  [161]
  [171]]

 [[161]
  [171]
  [  1]]

 [[171]
  [  1]
  [323]]]
[[[127]
  [182]
  [  3]]

 [[182]
  [  3]
  [ 13]]

 [[  3]
  [ 13]
  [161]]]
[[[ 61.30219  ]
  [152.73769  ]
  [147.60945  ]]

 [[163.30173  ]
  [162.45956  ]
  [ -3.0674393]]

 [[119.66304  ]
  [ 68.27524  ]
  [320.58044  ]]]


In [36]:

res=[]
for i in range(len(result)):
    predicted_word = ''
    for j in range(len(result[i])):
     for word, index in tokenizer.word_index.items():
        if index == int(result[i][j][0]):
          predicted_word = predicted_word+' '+word
          break
    res.append(predicted_word)
for i in res:
    print(i)

 democracy register power
 i’m covid
 everyone like political
